imports:
    - { resource: config.yml }

framework:
    router:
        resource: "%kernel.root_dir%/config/routing_dev.yml"
        strict_requirements: true
    profiler: { only_exceptions: false }

web_profiler:
    toolbar: true
    intercept_redirects: false

monolog:
    handlers:
        main:
            type:   stream
            path:   "%kernel.logs_dir%/%kernel.environment%.log"
            level:  debug
        console:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: INFO
                VERBOSITY_VERY_VERBOSE: DEBUG
            channels: ["!doctrine"]
        console_very_verbose:
            type:   console
            bubble: false
            verbosity_levels:
                VERBOSITY_VERBOSE: NOTICE
                VERBOSITY_VERY_VERBOSE: NOTICE
                VERBOSITY_DEBUG: DEBUG
            channels: ["doctrine"]
        # uncomment to get logging in your browser
        # you may have to allow bigger header sizes in your Web server configuration


assetic:
    use_controller: true

swiftmailer:
    spool:     { type: memory }
    transport: smtp
    host:      mailtrap.io
    username:  249292aabd72c6e7a
    password:  4f93dc4a1cdeb1
    auth_mode: cram-md5
    port: 2525

parameters:
    mailer_expeditor:  ua@ua.fr

    price.ticket.full: 1500
    price.ticket.reduced: 1000
    price.tshirt: 1000

    payment.stripe.secret: sk_test_ESrxq50Bw3NLh3atqmCfjdOI
    payment.stripe.publishable: pk_test_fftlf9QPXZcnn5DD9bE8Gg9f

    hashids.secret: 1-lE*bAWeXYS7Bz0BEEi-f87w
    hashids.minSize: 4

    reducedPriceDomains:
        - "utt.fr"
        - "utc.fr"
        - "utbm.fr"

    maximumPlayerNumber: 300