security:
    encoders:
        AppBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        player:
            entity:
                class: AppBundle:Player
                property: nickname

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
            provider: player
            form_login:
                login_path: /
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
