security:
    encoders:
        AppBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        player:
            entity:
                class: AppBundle\Entity\Player
                property: nickname

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~

            form_login:
                provider: player
                login_path: /
                always_use_default_target_path: true
                default_target_path:            /profile
                check_path: /login_check
                csrf_provider: security.csrf.token_manager
            logout:
                path:   /logout
                target: /