security:
    encoders:
        AppBundle\Entity\Player:
            algorithm: bcrypt

    providers:
        in_memory:
            memory: ~

    firewalls:
        dev:
            pattern: ^/(_(profiler|wdt|error)|css|images|js)/
            security: false

        main:
            anonymous: ~
